import pandas as pd
import os

def load_weather_data(data_dir):
    """
    Reads and combines relevant weather data files.
    Performs basic cleaning: removes missing values and unifies by date.
    Returns a DataFrame ready for analysis and modeling.
    """
    # Load only the daily mean temperature from the CSV file
    path = os.path.join(data_dir, 'TG_SOUID121044_1.csv')
    df = pd.read_csv(path, sep=';', skipinitialspace=True)
    # Rename columns for clarity
    df = df.rename(columns={"DATE": "DATE", "TG": "TG"})
    # Convert TG to numeric and mark missing values (-9999)
    df['TG'] = pd.to_numeric(df['TG'], errors='coerce')
    df = df[df['TG'] != -9999]
    # Convert TG from tenths to degrees Celsius
    df['TG'] = df['TG'] / 10.0
    # Keep only date and TG
    df = df[['DATE', 'TG']]
    # Reset index and return clean DataFrame
    df = df.reset_index(drop=True)
    return df

def create_lagged_features(df, n_lags=3):
    """
    Creates a DataFrame with lagged TG features for prediction.
    Each row contains TG(t), TG(t-1), TG(t-2), ..., TG(t-n_lags).
    Removes rows with missing values generated by the shift.
    """
    df_lagged = df.copy()
    for lag in range(1, n_lags+1):
        df_lagged[f'TG_lag_{lag}'] = df_lagged['TG'].shift(lag)
    # Remove rows with missing values
    df_lagged = df_lagged.dropna().reset_index(drop=True)
    # Keep only relevant columns
    cols = ['DATE', 'TG'] + [f'TG_lag_{lag}' for lag in range(1, n_lags+1)]
    return df_lagged[cols]

def load_datasets(data_dir):
    """
    Loads train_data.csv, val_data.csv, and test_data.csv files from the specified directory.
    Returns three DataFrames: train_df, val_df, test_df
    """
    train_path = os.path.join(data_dir, "train_data.csv")
    val_path = os.path.join(data_dir, "val_data.csv")
    test_path = os.path.join(data_dir, "test_data.csv")
    train_df = pd.read_csv(train_path)
    val_df = pd.read_csv(val_path)
    test_df = pd.read_csv(test_path)
    return train_df, val_df, test_df

